# Generated by Django 4.2.3 on 2023-07-14 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woman', models.BooleanField(default=False, verbose_name='여자전문의')),
                ('night_care', models.BooleanField(default=False, verbose_name='야간진료')),
                ('saturday_treatment', models.BooleanField(default=False, verbose_name='토요일 진료')),
                ('holiday_treatment', models.BooleanField(default=False, verbose_name='공휴일 진료')),
                ('sunday_care', models.BooleanField(default=False, verbose_name='일요일 진료')),
                ('latitude', models.FloatField(default=0.0, verbose_name='위도')),
                ('longtitude', models.FloatField(default=0.0, verbose_name='경도')),
                ('name', models.CharField(max_length=30, verbose_name='병원 이름')),
                ('content', models.TextField(null=True, verbose_name='병원 소개 내용')),
                ('adress', models.CharField(max_length=200, verbose_name='병원 주소')),
                ('image', models.ImageField(default=None, null=True, upload_to='hospital/', verbose_name='병원 소개 이미지')),
                ('waiting', models.IntegerField(default=0, verbose_name='대기자수')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('where', models.CharField(choices=[('서울특별시', '서울특별시'), ('경기도', '경기도'), ('인천광역시', '인천광역시'), ('강원특별자치도', '강원특별자치도'), ('대전광역시', '대전광역시'), ('세종특별자치도', '세종특별자치도'), ('충청남도', '충청남도'), ('충청북도', '충청북도'), ('부산광역시', '부산광역시'), ('울산광역시', '울산광역시'), ('경상남도', '경상남도'), ('경상북도', '경상북도'), ('대구광역시', '대구광역시'), ('광주광역시', '광주광역시'), ('전라남도', '전라남도'), ('전라북도', '전라북도'), ('제주특별자치도', '제주특별자치도')], default='', max_length=10, verbose_name='병원 주소')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(null=True, verbose_name='평점')),
                ('title', models.CharField(max_length=20, null=True, verbose_name='제목')),
                ('comment', models.TextField(verbose_name='내용')),
                ('writer', models.CharField(max_length=20, null=True, verbose_name='작성자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.hospital', verbose_name='리뷰 대상 병원')),
            ],
        ),
    ]
