# Generated by Django 4.2.3 on 2023-07-14 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitalapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='reservated_users',
            field=models.ManyToManyField(related_name='reservated_users', to=settings.AUTH_USER_MODEL, verbose_name='이 병원에 예약한 사용자'),
        ),
    ]
